# Project
group=com.mrcrayfish

# Java
java_version=25

# Common
minecraft_version=26.2
neo_form_version=26.2-1

# Fabric
fabric_version=0.152.2+26.2
fabric_loader_version=0.19.3
fabric_minecraft_version_range=~26.2-

# NeoForge
neoforge_version=26.2.0.6-beta
neoforge_version_range=[26.2,)
neoforge_loader_version_range=[2,)

# Mod options
mod_version=1.1.0
mod_name=MrCrayfish's Furniture Mod: Refurbished
mod_author=MrCrayfish
mod_id=refurbished_furniture
mod_desc=The next generation of MrCrayfish's Furniture Mod, built from the ground up with brand-new blocks, models, original sounds, and gameplay mechanics. Experience the new yet familiar charm of the original mod, and furnish your house with the hundreds of new and original decorations and functional blocks. Jump into new gameplay mechanics with the introduction of the electricity system to power all your appliances and electronics.
mod_homepage=https://mrcrayfish.com/mods/furniture_refurbished
mod_source=https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished
mod_issues=https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/issues
mod_license=MIT

# Dependency options
framework_version=0.14.1
jei_version=30.1.0.10
jei_minecraft_version=26.2
crafttweaker_version=21.0.2
crafttweaker_minecraft_version=1.21.1
catalogue_version=1.12.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false